version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zyoris
    ports:
      - '5432:5432'
    volumes:
      - zyoris_postgres_data:/var/lib/postgresql/data

volumes:
  zyoris_postgres_data:
