import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface PDFExportOptions {
  title: string;
  type: string;
  generatedBy: string;
  role: string;
  headers: string[];
  rows: (string | number)[][];
  summary: string;
}

export function generateAndDownloadPDF(options: PDFExportOptions) {
  const doc = new jsPDF();

  // Brand Header
  doc.setFillColor(30, 41, 59); // slate-800
  doc.rect(0, 0, 210, 30, "F");
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text("ZINDLE", 14, 18);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text("SECURE WORKFORCE INTELLIGENCE REPORT", 14, 25);

  // Report Title & Metadata
  doc.setTextColor(15, 23, 42); // slate-900
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(options.title, 14, 45);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(`Generated By: ${options.generatedBy} (${options.role})`, 14, 52);
  doc.text(`Date: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, 14, 58);

  // Summary section
  doc.setFillColor(241, 245, 249); // slate-100
  doc.roundedRect(14, 65, 182, 18, 2, 2, "F");
  doc.setTextColor(51, 65, 85); // slate-700
  doc.setFont("helvetica", "bold");
  doc.text("Summary Insight:", 18, 73);
  doc.setFont("helvetica", "normal");
  doc.text(options.summary, 18, 79);

  // Table
  autoTable(doc, {
    startY: 90,
    head: [options.headers],
    body: options.rows,
    theme: "striped",
    headStyles: {
      fillColor: [37, 99, 235], // blue-600
      textColor: 255,
      fontStyle: "bold"
    },
    styles: {
      fontSize: 9,
      cellPadding: 4
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252] // slate-50
    }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Zindle AI Copilot — Confidential & Proprietary — Page ${i} of ${pageCount}`,
      105,
      285,
      { align: "center" }
    );
  }

  // Save document
  const filename = `${options.title.toLowerCase().replace(/[^a-z0-9]/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
}
